### ISSUE TITLE
Setup TravisCI and Coveralls to see Code coverage

### ISSUE THREAD

**Issue by jcubic** [piecioshka/simple-data-table#4]
This was never executed, follow the link:
[![coveralls](https://coveralls.io/repos/github/piecioshka/simple-data-table/badge.svg?branch=master)](https://coveralls.io/github/piecioshka/simple-data-table?branch=master)

You can see the setup in this [simple example library](https://github.com/jcubic/open-source-library) (instead of make npm scripts).

**Comment by jcubic** [comment]
Why you don't run your tests from Travis? your `.travis.yaml` is empty. Check https://travis-ci.org/piecioshka/simple-data-table (build are empty). You need to add script that need to be run by travis. Your build badge just do nothing.

**Comment by jcubic** [comment]
you don't run code coverage from local machine you run it from travis using:

You need to add this to .travis.yaml otherwise build and coverage badges are usless:

```yaml
install:
  - npm install
script:
  - npm run lint
  - npm test
after_script:
  - npm run coverage && npm run report-coverage
```
